//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zero_hunger.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class food
    {
        public int id { get; set; }
        public int resturent_user_id { get; set; }
        public string food_name { get; set; }
        public string image_link { get; set; }
        public int qty { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
